export const vi = {
  hello: 'Xin chào',
  Example: 'Ví dụ',
  Default: 'Mặc định',
  Property: 'Thuộc tính',
  Description: 'Mô tả',
  Type: 'Loại',
  API: 'API',
  Size: 'Kích thước',
  Sizes: 'Kích thước',
  Icon: 'Biểu tượng',
  Loading: 'Đang tải',
  Disabled: 'Vô hiệu hóa',
  Appearance: 'Hình dáng',
  Status: 'Trạng thái',
  'Avatar Group': 'Nhóm Avatar',

  // Header
  Components: 'Thành phần',
  Blog: 'Bài viết',
  Language: 'Ngôn ngữ',

  // Tabs
  Examples: 'Ví dụ',
  Code: 'Code',
  Usage: 'Sử dụng',

  dropdown: {
    title: 'Menu thả xuống',
    description:
      'Menu thả xuống hiển thị danh sách các hành động hoặc tùy chọn cho người dùng.',
  },

  // Avatar
  avatar: {
    title: 'Avatar',
    description: 'Hiển thị một hình ảnh và tên người dùng.',
  },
  // Avatar API
  'Indicates the shape of the avatar': 'Chỉ ra hình dạng của avatar',
  'Defines the size of the avatar': 'Xác định kích thước của avatar',
  "Indicates a user's online status": 'Chỉ ra trạng thái trực tuyến của người dùng',
  'Defines the number of avatars you want show': 'Xác định số lượng avatar bạn muốn hiển thị',



  // Button
  Button: 'Button',
  Buttons: 'Buttons',
  button: {
    title: 'Button',
    description:
      'Một button kích hoạt một sự kiện hoặc hành động. Nó giúp cho người dùng biết điều gì sẽ xảy ra tiếp theo.',
  },
  // Button API
  'Different button styles can be generated by setting Button properties.': 'Các kiểu button khác nhau có thể được tạo ra bằng cách thiết lập các thuộc tính Button.',
  'The title of the button': 'Tiêu đề của button',
  'The type of the button': 'Kiểu của button',
  'Set the icon component of button': 'Thiết lập icon của button',
  'Can be set button shape': 'Có thể thiết lập hình dạng của button',
  'The size of the button': 'Kích thước của button',
  'Disabled state of button': 'Trạng thái không hoạt động của button',
  'Whether the button is loading': 'Khi button đang tải',
  'The callback function when the button is clicked': 'Hàm gọi lại khi button được nhấn',
  // Button Usage
  'Buttons are triggers for events or actions. They’re commonly used as part of larger components or patterns such as forms or modal dialogs.': 'Các button là các trigger cho các sự kiện hoặc hành động. Nó được dùng thường xuyên như một phần của các thành phần hoặc mẫu như form hoặc hộp thoại modal.',
  'Buttons are typically used to perform actions that are not directly related to the content of the page. For example, a button can be used to open a modal dialog or to trigger an action on a form.': 'Các button thường được dùng để thực hiện các hành động không liên quan đến nội dung của trang. Ví dụ, một button có thể được sử dụng để mở hộp thoại modal hoặc gọi lại một hành động trên một form.',
  'move users through a sequence of screens': 'di chuyển người dùng qua một chuỗi màn hình',
  'perform an action': 'thực hiện một hành động',
  'open a modal dialog': 'mở một hộp thoại modal',
  'submit a form': 'gửi một form',


  // Banner
  banner: {
    title: 'Banner',
    description: 'Banner hiển thị thông báo nổi bật ở đầu màn hình.',
  },
  'Content to be shown': 'Nội dung sẽ được hiển thị',
  'Visual style to be used for the banner': 'Kiểu hiển thị để sử dụng cho banner',
  'Show icon of banner': 'Hiển thị biểu tượng của banner',

  // Badge
  badge: {
    title: 'Badge',
    description: 'Giá trị số hoặc mô tả trạng thái cho các phần tử.',
  },
  'The children you want to show badge': 'Phần tử con muốn hiển thị badge',
  'Affects the visual style of the badge': 'Kiểu hiển thị của badge',
  'The maximum number of number to display': 'Số lượng tối đa có thể hiển thị',
  'The size of the badge': 'Kích thước của badge',
  'The icon to display': 'Biểu tượng để hiển thị',
  'The direction of the badge': 'Hướng của badge',
  'The position of the badge': 'Toạ độ của badge',

  // Breadcrumb
  breadcrumb: {
    title: 'Breadcrumb',
    description: "Breadcrumbs là một hệ thống điều hướng được sử dụng để hiển thị vị trí của người dùng trong một trang web hoặc ứng dụng.",
  },
  'Contains child elements including the Breadcrumb.Item.': 'Chứa phần tử con bao gồm các Breadcrumb.Item.',
  'The separator between Breadcrumb.Item elements.': 'Dấu phân cách giữa các phần tử Breadcrumb.Item.',
  'The content of the Breadcrumb': 'Nội dung của Breadcrumb',
  'Target of hyperlink': 'Đường dẫn liên kết đến trang đó',

  // Checkbox
  checkbox: {
    title: 'Checkbox',
    description: 'Checkbox cho phép người dùng chọn một hoặc nhiều tùy chọn.',
  },
  'Id assigned to checkbox': 'Id được gán cho checkbox',
  'Content of the checkbox': 'Nội dung của checkbox',
  'The size of the checkbox': 'Kích thước của checkbox',
  'The checked state of the checkbox': 'Trạng thái được chọn của checkbox',
  'The function to call when the checkbox is clicked': 'Hàm được gọi khi checkbox được nhấp',

  // Flag
  flag: {
    title: 'Flag',
    description: 'Flag được sử dụng để xác nhận, cảnh báo và xác nhận yêu cầu tương tác người dùng tối thiểu.',
  },
  'The bold text shown at the top of the flag': 'Văn bản in đậm được hiển thị ở đầu của flag',
  'The secondary content shown below the flag title': 'Nội dung phụ được hiển thị dưới tiêu đề của flag',
  'Array of clickable actions to be shown at the bottom of the flag': 'Mảng các hành động clickable được hiển thị dưới của flag',
  'Visual style to be used for the flag': 'Kiểu hiển thị để sử dụng cho flag',
  'array attributes of <a> tag': 'mảng thuộc tính của thẻ <a>',
};
