export const vi = {
  hello: 'Xin chào',
  Example: 'Ví dụ',
  Default: 'Mặc định',
  Property: 'Thuộc tính',
  Description: 'Mô tả',
  Type: 'Loại',
  API: 'API',
  Size: 'Kích thước',
  Sizes: 'Kích thước',
  Icon: 'Biểu tượng',
  Loading: 'Đang tải',
  Disabled: 'Vô hiệu hóa',
  Appearance: 'Hình dáng',
  Status: 'Trạng thái',
  'Avatar Group': 'Nhóm Avatar',
  Basic: 'Cơ bản',
  Actions: 'Hành động',
  Overflow: 'Tràn ngăn',
  Offset: 'Độ lệch',
  Warning: 'Cảnh báo',
  Error: 'Lỗi',
  Announcement: 'Thông báo',
  Separator: 'Phân cách',
  Controller: 'Bộ điều khiển',
  Direction: 'Hướng',
  Flip: 'Lật',
  Rotate: 'Xoay',
  Animation: 'Hiệu ứng',
  'Strict close': 'Đóng nghiêm ngặt',
  'Default selected index': 'Chỉ số mặc định được chọn',
  Group: 'Nhóm',
  Checked: 'Được chọn',
  Controlled: 'Điều khiển được',
  Resize: 'Thay đổi kích thước',
  'Max length': 'Độ dài tối đa',

  // Header
  Components: 'Thành phần',
  Blog: 'Bài viết',
  Language: 'Ngôn ngữ',

  // Tabs
  Examples: 'Ví dụ',
  Code: 'Code',
  Usage: 'Sử dụng',

  dropdown: {
    title: 'Dropdown',
    description: 'Dropdown hiển thị danh sách các hành động hoặc tùy chọn cho người dùng.',
  },

  // Avatar
  avatar: {
    title: 'Avatar',
    description: 'Hiển thị một hình ảnh và tên người dùng.',
  },
  // Avatar API
  'Indicates the shape of the avatar': 'Chỉ ra hình dạng của avatar',
  'Defines the size of the avatar': 'Xác định kích thước của avatar',
  "Indicates a user's online status": 'Chỉ ra trạng thái trực tuyến của người dùng',
  'Defines the number of avatars you want show': 'Xác định số lượng avatar bạn muốn hiển thị',

  // Button
  Button: 'Button',
  Buttons: 'Buttons',
  button: {
    title: 'Button',
    description:
      'Một button kích hoạt một sự kiện hoặc hành động. Nó giúp cho người dùng biết điều gì sẽ xảy ra tiếp theo.',
  },
  // Button API
  'Different button styles can be generated by setting Button properties.':
    'Các kiểu button khác nhau có thể được tạo ra bằng cách thiết lập các thuộc tính Button.',
  'The title of the button': 'Tiêu đề của button',
  'The type of the button': 'Kiểu của button',
  'Set the icon component of button': 'Thiết lập icon của button',
  'Can be set button shape': 'Có thể thiết lập hình dạng của button',
  'The size of the button': 'Kích thước của button',
  'Disabled state of button': 'Trạng thái không hoạt động của button',
  'Whether the button is loading': 'Khi button đang tải',
  'The callback function when the button is clicked': 'Hàm gọi lại khi button được nhấn',
  // Button Usage
  'Buttons are triggers for events or actions. They’re commonly used as part of larger components or patterns such as forms or modal dialogs.':
    'Các button là các trigger cho các sự kiện hoặc hành động. Nó được dùng thường xuyên như một phần của các thành phần hoặc mẫu như form hoặc hộp thoại modal.',
  'Buttons are typically used to perform actions that are not directly related to the content of the page. For example, a button can be used to open a modal dialog or to trigger an action on a form.':
    'Các button thường được dùng để thực hiện các hành động không liên quan đến nội dung của trang. Ví dụ, một button có thể được sử dụng để mở hộp thoại modal hoặc gọi lại một hành động trên một form.',
  'move users through a sequence of screens': 'di chuyển người dùng qua một chuỗi màn hình',
  'perform an action': 'thực hiện một hành động',
  'open a modal dialog': 'mở một hộp thoại modal',
  'submit a form': 'gửi một form',

  // Banner
  banner: {
    title: 'Banner',
    description: 'Banner hiển thị thông báo nổi bật ở đầu màn hình.',
  },
  'Content to be shown': 'Nội dung sẽ được hiển thị',
  'Visual style to be used for the banner': 'Kiểu hiển thị để sử dụng cho banner',
  'Show icon of banner': 'Hiển thị biểu tượng của banner',

  // Badge
  badge: {
    title: 'Badge',
    description: 'Giá trị số hoặc mô tả trạng thái cho các phần tử.',
  },
  'The children you want to show badge': 'Phần tử con muốn hiển thị badge',
  'Affects the visual style of the badge': 'Kiểu hiển thị của badge',
  'The maximum number of number to display': 'Số lượng tối đa có thể hiển thị',
  'The size of the badge': 'Kích thước của badge',
  'The icon to display': 'Biểu tượng để hiển thị',
  'The direction of the badge': 'Hướng của badge',
  'The position of the badge': 'Toạ độ của badge',

  // Breadcrumb
  breadcrumb: {
    title: 'Breadcrumb',
    description:
      'Breadcrumbs là một hệ thống điều hướng được sử dụng để hiển thị vị trí của người dùng trong một trang web hoặc ứng dụng.',
  },
  'Contains child elements including the Breadcrumb.Item.':
    'Chứa phần tử con bao gồm các Breadcrumb.Item.',
  'The separator between Breadcrumb.Item elements.':
    'Dấu phân cách giữa các phần tử Breadcrumb.Item.',
  'The content of the Breadcrumb': 'Nội dung của Breadcrumb',
  'Target of hyperlink': 'Đường dẫn liên kết đến trang đó',

  // Checkbox
  checkbox: {
    title: 'Checkbox',
    description: 'Checkbox cho phép người dùng chọn một hoặc nhiều tùy chọn.',
  },
  'Id assigned to checkbox': 'Id được gán cho checkbox',
  'Content of the checkbox': 'Nội dung của checkbox',
  'The size of the checkbox': 'Kích thước của checkbox',
  'The checked state of the checkbox': 'Trạng thái được chọn của checkbox',
  'The function to call when the checkbox is clicked': 'Hàm được gọi khi checkbox được nhấp',

  // Divider
  divider: {
    title: 'Divider',
    description: 'Divider là một đường mảnh được sử dụng để phân tách nội dung.',
  },
  'Show icon in center': 'Hiển thị biểu tượng trong trung tâm',
  'Direction of divider': 'Hướng của divider',

  // Flag
  flag: {
    title: 'Flag',
    description:
      'Flag được sử dụng để xác nhận, cảnh báo và xác nhận yêu cầu tương tác người dùng tối thiểu.',
  },
  'The bold text shown at the top of the flag': 'Văn bản in đậm được hiển thị ở đầu của flag',
  'The secondary content shown below the flag title':
    'Nội dung phụ được hiển thị dưới tiêu đề của flag',
  'Array of clickable actions to be shown at the bottom of the flag':
    'Mảng các hành động clickable được hiển thị dưới của flag',
  'Visual style to be used for the flag': 'Kiểu hiển thị để sử dụng cho flag',
  'array attributes of <a> tag': 'mảng thuộc tính của thẻ <a>',

  // Icon
  icon: {
    title: 'Icon',
    description: 'Icon là sự thể hiện trực quan của một tệp, ứng dụng hoặc hành động.',
  },
  'The name of the icon': 'Tên của icon',
  'The size of the icon': 'Kích thước của icon',
  'The color of the icon': 'Màu sắc của icon',
  'The rotate of the icon': 'Xoay icon',
  'The flip of the icon': 'Lật icon',
  'The animation of the icon': 'Hiệu ứng của icon',

  // Image
  image: {
    title: 'Image',
    description: 'Image được sử dụng để hiển thị hình ảnh.',
  },
  'The source of the image.': 'Nguồn của hình ảnh.',
  'The alternative text of the image.': 'Nội dung mô tả của hình ảnh.',
  'Whether the image should be lazy loaded.': 'Hình ảnh có thể được tải nhanh hay không.',
  'The type of the image.': 'Loại của hình ảnh.',
  'The decoding of the image.': 'Giải mã của hình ảnh.',
  'The source set of the image.': 'Nguồn của hình ảnh.',
  'The aspect ratio of the image.': 'Tỷ lệ khung hình ảnh.',

  // Lozenge
  lozenge: {
    title: 'Lozenge',
    description:
      'Một lozenge là một chỉ báo trực quan được sử dụng để làm nổi bật trạng thái của một mục để nhận dạng nhanh.',
  },
  'Elements to be rendered inside the lozenge': 'Các phần tử được hiển thị trong lozenge',
  'The appearance of the lozenge': 'Kiểu hiển thị của lozenge',
  'Determines whether to apply the bold style or not':
    'Xác định có phải áp dụng kiểu in đậm hay không',
  'max-width of lozenge container': 'chiều rộng tối đa của lozenge',

  // Modal
  modal: {
    title: 'Modal',
    description:
      'Modal hiển thị nội dung yêu cầu tương tác của người dùng, trong một lớp phía trên trang.',
  },
  'Whether the modal dialog is visible or not': 'Có hiển thị hộp thoại modal hay không',
  'Function to close the modal dialog': 'Hàm đóng hộp thoại modal',
  'Whether the modal dialog can be closed by clicking outside of it':
    'Có thể hộp thoại modal được đóng bằng cách nhấp vào ngoài nó',
  'The content of the modal header': 'Nội dung của tiêu đề hộp thoại modal',
  'Whether the modal header has a close button': 'Tiêu đề hộp thoại modal có có nút đóng hay không',
  'The content of the modal body': 'Nội dung của phần thân hộp thoại modal',
  'The content of the modal footer': 'Nội dung của phần chân hộp thoại modal',
  'The text of the OK button': 'Văn bản của nút OK',
  'The text of the Cancel button': 'Văn bản của nút Cancel',
  'Specify a function that will be called when a user clicks the OK button':
    'Xác định một hàm sẽ được gọi khi người dùng nhấp vào nút OK',
  'Specify a function that will be called when a user clicks mask, close button on top right or Cancel button':
    'Xác định một hàm sẽ được gọi khi người dùng nhấp vào mặt nạ, nút đóng ở phía trên bên phải hoặc nút Cancel',

  // Pagination
  pagination: {
    title: 'Pagination',
    description:
      'Pagination cho phép bạn chia lượng lớn nội dung thành các phần nhỏ hơn trên nhiều trang.',
  },
  'Total number of data items': 'Tổng số các mục dữ liệu',
  'Default page size': 'Kích thước trang mặc định',
  'Default initial page number': 'Số trang mặc định ban đầu',

  radio: {
    title: 'Radio',
    description:
      'Radio cho phép mọi người chỉ chọn một tùy chọn trong số các lựa chọn. Radio thường được hiển thị trong một nhóm radio.',
  },
  'Specifies the name of the radio button.': 'Xác định tên của nút radio.',
  'Specifies the value of the radio button.': 'Xác định giá trị của nút radio.',
  'Should be pre-selected when the page loads': 'Có được chọn trước khi trang tải lên',
  'Should be disabled when the page loads': 'Có được vô hiệu khi trang tải lên',
  'Called when the radio button is clicked': 'Được gọi khi nút radio được nhấp',
  'Specifies the appearance of the radio button.': 'Xác định kiểu hiển thị của nút radio.',

  // Range
  range: {
    title: 'Range',
    description: 'Range cho phép người dùng chọn một giá trị gần đúng trên một thanh trượt',
  },
  'Sets the minimum value of the range.': 'Thiết lập giá trị tối thiểu của range',
  'Sets the maximum value of the range.': 'Thiết lập giá trị tối đa của range',
  'Sets the step value of the range.': 'Thiết lập giá trị bước của range',
  'Sets the default value if range is not set.':
    'Thiết lập giá trị mặc định nếu range không được thiết lập',
  'Called when the range value changes.': 'Được gọi khi giá trị range thay đổi',
  'Disables the range.': 'Vô hiệu range',

  // Tabs
  tabs: {
    title: 'Tabs',
    description:
      'Các tab được sử dụng để sắp xếp nội dung bằng cách nhóm các thông tin tương tự trên cùng một trang.',
  },
  'The children elements of the Tabs.': 'Các phần tử con của Tabs',
  'The title of the Tabs.': 'Tiêu đề của Tabs',
  'The default tab to be selected.': 'Tab mặc định được chọn',

  // Table
  table: {
    title: 'Table',
    description: 'Table là một tập hợp dữ liệu được sắp xếp theo hàng và cột.',
  },
  'Elements to be rendered inside the Table': 'Các phần tử được hiển thị trong Table',
  'Data to be rendered inside the Table': 'Dữ liệu được hiển thị trong Table',
  'Elements to be rendered inside the Column': 'Các phần tử được hiển thị trong Column',
  'Header of the Column': 'Tiêu đề của Column',
  'Key of the data table': 'Key của bảng dữ liệu',

  // Spinner
  spinner: {
    title: 'Spinner',
    description:
      'Spinner là một biểu tượng quay động cho phép người dùng biết nội dung đang được tải.',
  },
  'Size of the spinner.': 'Kích thước của spinner',

  // TextArea
  textArea: {
    title: 'Text area',
    description:
      'Một vùng văn bản cho phép người dùng nhập văn bản dạng dài kéo dài trên nhiều dòng.',
  },
  'Enables the resizing of the textarea': 'Cho phép thay đổi kích thước của vùng văn bản',
  'Sets the field as uneditable, with a changed hover state.':
    'Thiết lập trường như không thể chỉnh sửa, với trạng thái chọn trên đã thay đổi.',
  'If true, prevents the value of the input from being edited.':
    'Nếu được bật sẽ ngăn chặn giá trị của đầu vào được chỉnh sửa.',
  'Set required for form that the field is part of.':
    'Thiết lập bắt buộc cho mẫu mà trường này là một phần của nó.',
  'Sets the maximum height of the textarea.': 'Thiết lập chiều cao tối đa của vùng văn bản',
  'The default value of the textarea': 'Giá trị mặc định của vùng văn bản',
  'Enables native spell check on the textarea element.':
    'Cho phép kiểm tra chính tả trên phần tử văn bản của textarea',

  // TextField
  textField: {
    title: 'Text field',
    description: 'Text field là đầu vào cho phép người dùng viết hoặc chỉnh sửa văn bản.',
  },
  'Name of the input element.': 'Tên của phần tử đầu vào',
  'Placeholder text to display in the text field whenever it is empty.':
    'Văn bản chứa để hiển thị trong trường văn bản khi trống',
  'Sets maximum width of input.': 'Thiết lập chiều rộng tối đa của đầu vào',
  'Handler called when the inputs value changes.': 'Handler được gọi khi giá trị đầu vào thay đổi',
  'Sets maximum length of input.': 'Thiết lập chiều dài tối đa của đầu vào',
  'Sets the field as to appear disabled, users will not be able to interact with the text field.':
    'Thiết lập trường như đang ẩn, người dùng sẽ không thể thao tác với trường văn bản',

  // Toggle
  toggle: {
    title: 'Toggle',
    description:
      'Toggle được sử dụng để xem hoặc chuyển đổi giữa các trạng thái đã bật hoặc đã tắt.',
  },
  'Handler to be called when native click event happens internally.':
    'Handler được gọi khi sự kiện click xảy ra ',
  'The value of the toggle.': 'Giá trị của toggle',
  'The icon to be displayed when the toggle is unchecked.':
    'Biểu tượng được hiển thị khi toggle được bỏ chọn',
  'The icon to be displayed when the toggle is checked.':
    'Biểu tượng được hiển thị khi toggle được chọn',
  'Skip navigation': 'Bỏ qua điều hướng',
};
