export const vi = {
  hello: 'Xin chào',
  Example: 'Ví dụ',
  Default: 'Mặc định',
  Property: 'Thuộc tính',
  Description: 'Mô tả',
  Type: 'Loại',
  API: 'API',
  Size: 'Kích thước',
  Sizes: 'Kích thước',
  Icon: 'Biểu tượng',
  Loading: 'Đang tải',
  Disabled: 'Vô hiệu hóa',
  Appearance: 'Hình dáng',
  Status: 'Trạng thái',
  'Avatar Group': 'Nhóm Avatar',

  // Header
  Components: 'Thành phần',
  Blog: 'Bài viết',
  Language: 'Ngôn ngữ',

  // Tabs
  Examples: 'Ví dụ',
  Code: 'Code',
  Usage: 'Sử dụng',

  dropdown: {
    title: 'Menu thả xuống',
    description:
      'Menu thả xuống hiển thị danh sách các hành động hoặc tùy chọn cho người dùng.',
  },

  // Avatar
  avatar: {
    title: 'Avatar',
    description: 'Hiển thị một hình ảnh và tên người dùng.',
  },
  // Avatar API
  'Indicates the shape of the avatar': 'Chỉ ra hình dạng của avatar',
  'Defines the size of the avatar': 'Xác định kích thước của avatar',
  "Indicates a user's online status": 'Chỉ ra trạng thái trực tuyến của người dùng',
  'Defines the number of avatars you want show': 'Xác định số lượng avatar bạn muốn hiển thị',



  // Button
  Button: 'Button',
  Buttons: 'Buttons',
  button: {
    title: 'Button',
    description:
      'Một button kích hoạt một sự kiện hoặc hành động. Nó giúp cho người dùng biết điều gì sẽ xảy ra tiếp theo.',
  },
  // Button API
  'Different button styles can be generated by setting Button properties.': 'Các kiểu button khác nhau có thể được tạo ra bằng cách thiết lập các thuộc tính Button.',
  'The title of the button': 'Tiêu đề của button',
  'The type of the button': 'Kiểu của button',
  'Set the icon component of button': 'Thiết lập icon của button',
  'Can be set button shape': 'Có thể thiết lập hình dạng của button',
  'The size of the button': 'Kích thước của button',
  'Disabled state of button': 'Trạng thái không hoạt động của button',
  'Whether the button is loading': 'Khi button đang tải',
  'The callback function when the button is clicked': 'Hàm gọi lại khi button được nhấn',
  // Button Usage
  'Buttons are triggers for events or actions. They’re commonly used as part of larger components or patterns such as forms or modal dialogs.': 'Các button là các trigger cho các sự kiện hoặc hành động. Nó được dùng thường xuyên như một phần của các thành phần hoặc mẫu như form hoặc hộp thoại modal.',
  'Buttons are typically used to perform actions that are not directly related to the content of the page. For example, a button can be used to open a modal dialog or to trigger an action on a form.': 'Các button thường được dùng để thực hiện các hành động không liên quan đến nội dung của trang. Ví dụ, một button có thể được sử dụng để mở hộp thoại modal hoặc gọi lại một hành động trên một form.',
  'move users through a sequence of screens': 'di chuyển người dùng qua một chuỗi màn hình',
  'perform an action': 'thực hiện một hành động',
  'open a modal dialog': 'mở một hộp thoại modal',
  'submit a form': 'gửi một form',


  // Banner
  banner: {
    title: 'Banner',
    description: 'Banner hiển thị thông báo nổi bật ở đầu màn hình.',
  }
};
